apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: read-swagger
rules:
- nonResourceURLs:
  - /swagger-2.0.0.pb-v1
  - /swagger.json
  - /swaggerapi
  - /swaggerapi/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-swagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-swagger
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated